version: '3.1'

services: 
    postgresdb:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=sicheres123Passwort
        volumes:
            - ./docker/database/dbscripts:/docker-entrypoint-initdb.d
            - postgres_data:/var/lib/postgresql/data
        ports:
            - 5432:5432
        networks: 
            - labelixNetwork
    postgres-keycloak:
        image: postgres
        restart: always
        volumes:
            - postgres-keycloak_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=password
        networks:
            - labelixNetwork
            
    keycloak:
        build:
            context: ./docker/keycloak
            dockerfile: ./Dockerfile
        restart: always
        command: -Dkeycloak.profile.feature.upload_scripts=enabled
        environment:
            - DB_VENDOR=POSTGRES
            - DB_ADDR=postgres-keycloak
            - DB_PORT=5432
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_SCHEMA=public
            - DB_PASSWORD=password
            - KEYCLOAK_IMPORT=/tmp/keycloak/realm.json
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=5pmna0
            - PROXY_ADDRESS_FORWARDING=true  
        ports:
            - 8180:8080
        volumes:
            - ./docker/keycloak/:/tmp/keycloak
            - ./docker/keycloak/material:/opt/jboss/keycloak/themes/material
        networks:
            - labelixNetwork
        depends_on:
            - postgres-keycloak

    webapi:
        build:
            context: ./backend/Labelix-Backend
            dockerfile: ./Labelix.WebAPI/Dockerfile
        restart: always
        ports:
            - 8080:80
        links: 
            - postgresdb
        volumes:
            - ./docker/backendData/Images:/app/Ressources/Images
            - ./docker/backendData/Labels:/app/Ressources/Labels
        networks: 
            - labelixNetwork
    
    frontend:
        build: 
            context: ./frontend/labelix-web-app
            dockerfile: ./Dockerfile
        restart: always
        ports: 
            - 4200:80
        links:
            - webapi
        networks: 
            - labelixNetwork
              
    reverseproxy:
        image: nginx
        restart: always
        ports:
            - 80:80
            - 443:443
        links:
            - webapi
        networks: 
            - labelixNetwork
        volumes:
          - /etc/letsencrypt:/etc/letsencrypt
          - ./docker/reverseproxy/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - webapi
          - keycloak

volumes: 
    postgres_data:
    postgres-keycloak_data:
networks: 
    labelixNetwork:
