version: '3.1'

services: 
    postgresdb:
        image: postgres
        restart: always
        environment:
            - POSTGRES_PASSWORD=sicheres123Passwort
        ports:
            - 5422:5432
        volumes:
            - ./docker/database/dbscripts:/docker-entrypoint-initdb.d
            - postgres_data:/var/lib/postgresql/data
        networks: 
            - labelixNetwork
    postgres-keycloak:
        image: postgres
        volumes:
            - postgres-keycloak_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=keycloak
            - POSTGRES_USER=keycloak
            - POSTGRES_PASSWORD=password
        networks:
            - labelixNetwork
    keycloak:
        image: jboss/keycloak
        command: -Dkeycloak.profile.feature.upload_scripts=enabled
        environment:
            - DB_VENDOR=POSTGRES
            - DB_ADDR=postgres-keycloak
            - DB_PORT=5432
            - DB_DATABASE=keycloak
            - DB_USER=keycloak
            - DB_SCHEMA=public
            - DB_PASSWORD=password
            - KEYCLOAK_IMPORT=/tmp/keycloak/realm_v2.json
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
        ports:
            - 8180:8080
        volumes:
            - ./docker/keycloak/:/tmp/keycloak
            - ./docker/keycloak/material:/opt/jboss/keycloak/themes/material
        networks:
            - labelixNetwork
        depends_on:
            - postgres-keycloak

    webapi:
        build:
            context: ./backend/Labelix-Backend
            dockerfile: ./Labelix.WebAPI/Dockerfile
        ports:
            - 8080:80
        links: 
            - postgresdb
        volumes:
            - ./docker/backendData/Images:/app/Ressources/Images
            - ./docker/backendData/Labels:/app/Ressources/Labels
        networks: 
            - labelixNetwork

    reverseproxy:
        build:
            context: ./docker/reverseproxy
            dockerfile: Dockerfile
        ports:
            - 80:80
        links:
            - webapi
        networks: 
            - labelixNetwork
volumes: 
    postgres_data:
    postgres-keycloak_data:
networks: 
    labelixNetwork: