create table ai_model_configs
(
    "Id"              integer generated by default as identity
        constraint "PK_ai_model_configs"
            primary key,
    "Name"            text,
    "DockerImageName" text,
    "Parameter"       text,
    "InputDirectory"  text,
    "OutputDirectory" text,
    "Options"         text
);

alter table ai_model_configs
    owner to postgres;

create table project_users
(
    "Id"         integer generated by default as identity
        constraint "PK_project_users"
            primary key,
    "ProjectKey" integer not null,
    "UserIdKey"  integer not null
);

alter table project_users
    owner to postgres;

create table projects
(
    "Id"                 integer generated by default as identity
        constraint "PK_projects"
            primary key,
    "Name"               text,
    "Description"        text,
    "CreationDate"       timestamp not null,
    "FinishedAnnotation" boolean   not null,
    "LabeledPath"        text
);

alter table projects
    owner to postgres;

create table users
(
    "Id"          integer generated by default as identity
        constraint "PK_users"
            primary key,
    "Keycloak_id" text
);

alter table users
    owner to postgres;

create table images
(
    "Id"        integer generated by default as identity
        constraint "PK_images"
            primary key,
    "ImagePath" text,
	"Height"    double precision not null,
    "Width"     double precision not null,
    "ProjectId" integer not null
        constraint "FK_images_projects_ProjectId"
            references projects
            on delete cascade
);

alter table images
    owner to postgres;

create index "IX_images_ProjectId"
    on images ("ProjectId");

create table labels
(
    "Id"        integer generated by default as identity
        constraint "PK_labels"
            primary key,
    "Name"      text,
    "Color"     text,
    "ProjectId" integer not null
        constraint "FK_labels_projects_ProjectId"
            references projects
            on delete cascade
);

alter table labels
    owner to postgres;

create index "IX_labels_ProjectId"
    on labels ("ProjectId");

create table project_ai_model_configs
(
    "Id"          integer generated by default as identity
        constraint "PK_project_ai_model_configs"
            primary key,
    "ProjectKey"  integer not null
        constraint "FK_project_ai_model_configs_projects_ProjectKey"
            references projects
            on delete cascade,
    "AIConfigKey" integer not null
        constraint "FK_project_ai_model_configs_ai_model_configs_AIConfigKey"
            references ai_model_configs
            on delete cascade
);

alter table project_ai_model_configs
    owner to postgres;

create index "IX_project_ai_model_configs_AIConfigKey"
    on project_ai_model_configs ("AIConfigKey");

create index "IX_project_ai_model_configs_ProjectKey"
    on project_ai_model_configs ("ProjectKey");
