create table if not exists ai_configs
(
	"Id" integer generated by default as identity
		constraint "PK_ai_configs"
			primary key,
	"Name" text,
	"DockerImageName" text,
	"Parameter" text,
	"InputDirectory" text,
	"OutputDirectory" text
);

alter table ai_configs owner to postgres;

create table if not exists projects
(
	"Id" integer generated by default as identity
		constraint "PK_projects"
			primary key,
	"Name" text,
	"Description" text,
	"CreationDate" timestamp not null,
	"FinishedAnnotation" boolean not null,
	"LabeledPath" text
);

alter table projects owner to postgres;

create table if not exists images
(
	"Id" integer generated by default as identity
		constraint "PK_images"
			primary key,
	"ImagePath" text,
	"ProjectId" integer not null
		constraint "FK_images_projects_ProjectId"
			references projects
				on delete cascade
);

alter table images owner to postgres;

create index if not exists "IX_images_ProjectId"
	on images ("ProjectId");

create table if not exists labels
(
	"Id" integer generated by default as identity
		constraint "PK_labels"
			primary key,
	"Name" text,
	"Color" text,
	"ProjectId" integer not null
		constraint "FK_labels_projects_ProjectId"
			references projects
				on delete cascade
);

alter table labels owner to postgres;

create index if not exists "IX_labels_ProjectId"
	on labels ("ProjectId");

create table if not exists "Project_AIConfigSet"
(
	"Id" integer generated by default as identity
		constraint "PK_Project_AIConfigSet"
			primary key,
	"ProjectKey" integer not null
		constraint "FK_Project_AIConfigSet_projects_ProjectKey"
			references projects
				on delete cascade,
	"AIConfigKey" integer not null
		constraint "FK_Project_AIConfigSet_ai_configs_AIConfigKey"
			references ai_configs
				on delete cascade
);

alter table "Project_AIConfigSet" owner to postgres;

create index if not exists "IX_Project_AIConfigSet_AIConfigKey"
	on "Project_AIConfigSet" ("AIConfigKey");

create index if not exists "IX_Project_AIConfigSet_ProjectKey"
	on "Project_AIConfigSet" ("ProjectKey");

