create table ai_configs
(
    "Id"              integer generated by default as identity
        constraint "PK_ai_configs"
            primary key,
    "Name"            text,
    "DockerImageName" text,
    "Parameter"       text,
    "InputDirectory"  text,
    "OutputDirectory" text
);

alter table ai_configs
    owner to postgres;

INSERT INTO public.ai_configs ("Id", "Name", "DockerImageName", "Parameter", "InputDirectory", "OutputDirectory") VALUES (3, 'Zebraerkennung', 'Nvidea/Zebraerkennung', '--gpu all --output-format coco', '/input', '/output');
INSERT INTO public.ai_configs ("Id", "Name", "DockerImageName", "Parameter", "InputDirectory", "OutputDirectory") VALUES (1, 'Affenerkennung', 'Nvidea/Affenerkennung', '--gpu all --output-format coco', '/input', '/output');
INSERT INTO public.ai_configs ("Id", "Name", "DockerImageName", "Parameter", "InputDirectory", "OutputDirectory") VALUES (2, 'Giraffenerkennung', 'Nvidea/Giraffenerkennung', '--gpu all --output-format coco', '/input', '/output');